// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mtinbtllstjuwzkutdif.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im10aW5idGxsc3RqdXd6a3V0ZGlmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDIyMDUxMDIsImV4cCI6MjA1Nzc4MTEwMn0.rlFaVVdIR5A0I9OiUOawym4_HexGXyAjBQSHS8dRdys";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);